### ISSUE TITLE
Deprecate this repo for jfrog/terraform-provider-artifactory

### ISSUE THREAD

**Issue by peters95** [atlassian/terraform-provider-artifactory#102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Please deprecate this repo for the official jfrog/terraform-provider-artifactory

**Comment by ttsangAtlassian** [comment]
Added a deprecation notice and redirect people to the JFrog provider https://github.com/atlassian/terraform-provider-artifactory/pull/103
