### ISSUE TITLE
setting `artifactory_group.user_names` to `[]` produces correct plan but doesn't take effect

### ISSUE THREAD

**Issue by antonmos** [atlassian/terraform-provider-artifactory#106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/jfrog/artifactory v2.6.12

### Affected Resource(s)

`artifactory_group`

### Terraform Configuration Files

```hcl
resource "artifactory_group" "power_users" {
  name      = "power-users"
  users_names = []
}

```

### Expected Behavior

Users will be removed from the group

### Actual Behavior

Plan is correct: 

```
Terraform will perform the following actions:

  # artifactory_group.platform_team will be updated in-place
  ~ resource "artifactory_group" "power_users" {
        admin_privileges = false
        auto_join        = false
        id               = "power-users"
        name             = "power-users"
        realm            = "internal"
      ~ users_names      = [
          - "user1", 
        ]
    }
```
But users are not removed after `terraform apply`
### Steps to Reproduce

1. create a group with terraform
1. add users via the UI
1. update terraform to `  users_names = []`
1. terraform apply

### References

* #0000

**Comment by jamestoyer** [comment]
Hi @antonmos,

This repo is deprecated in favour of github.com/jfrog/terraform-provider-artifactory. If you're having issues, your best bet is to post there

**Comment by antonmos** [comment]
thank you! opened https://github.com/jfrog/terraform-provider-artifactory/issues/253
