### ISSUE TITLE
Add Examples and FAQ

### ISSUE THREAD

**Issue by MLC-Mat** [atlassian/terraform-provider-artifactory#14]
Could a small number of examples of usage within Terraform be included in the readme please?

**Comment by dillon-giacoppo** [comment]
I agree that there should be more documentation including examples but also an FAQ. Whilst this is added, you will find examples for each resource in the respective resource_\*\_test.go files. The absolute source of truth will always be the schema as defined in the resource_\*\.go file and I strongly recommend checking this file out if you want an in depth look at each resource.

**Comment by amanjeev** [comment]
LOL! I opened another one for the same reason. Sorry. I agree with @MLC-Mat. If not a lot, at least just a minor example would be nice.

**Comment by dillon-giacoppo** [comment]
Docs are now at https://github.com/atlassian/terraform-provider-artifactory/tree/master/docs Please raise individual tickets for errors/improvements. Thanks!

**Comment by amanjeev** [comment]
Thank you so much!
