### ISSUE TITLE
Documentation on how to use this plugin

### ISSUE THREAD

**Issue by amanjeev** [atlassian/terraform-provider-artifactory#16]
The [README](https://github.com/atlassian/terraform-provider-artifactory/blob/master/README.md) of this repo does not contain the example usage directions.

I would like to have a section in the README of this repo that gives an example of how to use this plugin. An example usage section is https://github.com/Ashald/terraform-provider-yaml#usage.

It will make life for future users much better. Thank you.

**Comment by dillon-giacoppo** [comment]
Duplicates #14
