### ISSUE TITLE
Remote repository does not support 'EnableTokenAuthentication' parameter

### ISSUE THREAD

**Issue by bsemperlotti** [atlassian/terraform-provider-artifactory#18]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The remote repository resource does not provide the `EnableTokenAuthentication` parameter for used for docker.

### New or Affected Resource(s)

Resource  `artifactory_remote_repository` is missing parameter `enable_token_authentication`

### Potential Terraform Configuration

```hcl
resource artifactory_remote_repository "docker_io_remote" {
  key                         = "docker-io-remote"
  description                 = "A remote access to the docker.io registry"
  notes                       = "A remote access to the docker.io registry"
  package_type                = "docker"
  enable_token_authentication = true
  url                         = "https://registry-1.docker.io/"
  repo_layout_ref             = "simple-default"
  includes_pattern            = "**/*"
  excludes_pattern            = ""
  property_sets               = ["artifactory"]
}
```

### References

NA

**Comment by dillon-giacoppo** [comment]
Changes have been pushed out in release v1.4.2. Thanks for the contribution!
