### ISSUE TITLE
Add support for XRay integration

### ISSUE THREAD

**Issue by Constantin07** [atlassian/terraform-provider-artifactory#26]
### Description

This is feature request.
Context: We've got JFrog Artifactory integrated with XRay product. Once this integration is enabled - there is a tick box available to enable indexing of repository in XRay.

It would be nice to add an attribute to toggle this switch.

### New or Affected Resource(s)
repository resources (local, remote)

### References
https://www.jfrog.com/confluence/display/RTF/Xray+Integration

![image](https://user-images.githubusercontent.com/11664677/53083661-4292e380-34f7-11e9-9563-eb50f3a1573c.png)

**Comment by Constantin07** [comment]
_Update:_ after contacting JFrog's support it looks like this can be done by the [create](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-CreateRepository) or [update](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateRepositoryConfiguration) repository REST API commands by adding the `"xrayIndex" : true` parameter to the [JSON](https://www.jfrog.com/confluence/display/RTF/Repository+Configuration+JSON) file although it's not yet documented officially.

**Comment by dillon-giacoppo** [comment]
This will be included in V2

**Comment by KierranM** [comment]
It's not documented for remote repos either, but it is possible to enable xray through the UI for remotes the same way you can for locals. I'd like to assume there API also supports setting it through the JSON (haven't confirmed if it works), but it'd be great to have remote support as well :)

**Comment by Constantin07** [comment]
Thanks @dillon-giacoppo 
@KierranM I've asked JFrog support to update the official docs. I hope this will be done soon.
