### ISSUE TITLE
Unable to create pull replication

### ISSUE THREAD

**Issue by KierranM** [atlassian/terraform-provider-artifactory#28]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8

### Affected Resource(s)

* artifactory_replication_config

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file.
terraform {
  version = ">=0.0.3"
}

variable "artifactory_url" {
  type = "string"
}

variable "artifactory_username" {
  type = "string"
}

variable "artifactory_password" {
  type = "string"
}

variable "remote_repo_url" {
  type = "string"
}

variable "remote_username" {
  type = "string"
}

variable "remote_password" {
  type = "string"
}

provider "artifactory" {
  url      = "${var.artifactory_url}"
  username = "${var.artifactory_username}"
  password = "${var.artifactory_password}"
}

resource "artifactory_remote_repository" "remote" {
  key             = "test-remote-replication"
  url             = "${var.remote_repo_url}"
  package_type    = "npm"
  username        = "${var.remote_username}"
  password        = "${var.remote_password}"
  repo_layout_ref = "npm-default"
}

resource "artifactory_replication_config" "npm-remote" {
  repo_key                 = "${artifactory_remote_repository.remote.key}"
  cron_exp                 = "0 0 * * * ?"
  enable_event_replication = true
  replications = [
    {
      url      = "${var.remote_repo_url}"
      username = "${var.remote_username}"
      password = "${var.remote_password}"
    },
  ]
}

```

### Expected Behaviour

A Pull replication configuration should be created on the remote repo to automatically pull artifacts from the remote artifactory instance.

### Actual Behaviour
```
* artifactory_replication_config.npm-remote: PUT https://<artifactory-domain>/artifactory/api/replications/multiple/test-remote-replication: 400 [{Status:400 Message:Invalid repository}]
```

### Steps to Reproduce

1.  Have 2 artifactory instances
1. Create npm local repo in source artifactory
1. `terraform apply`

### Other Notes

This seems to be an issue with the `/api/replications/multiple/<repo>` endpoint not supporting remotes (despite the rest documentation stating it supports `local-cached` repos.
I'm able to send the replication config as a JSON payload to the `/api/replications/<repo>` and it creates successfully.

I'm going to raise a support request with JFrog, as I believe the `multiple` endpoint should work for creating pull replications for remotes.

**Comment by KierranM** [comment]
I've had a response from JFrog which amounts to:

> Thank you for your reply and reporting this.
We have reproduced the same behaviour and the mentioned API's by you, indeed are supported only with local repositories.
We have updated the wiki. Thank you again for reporting this.

So it would seem that the `/multiple` endpoint cannot be used with `remote` repositories. I don't know whether the best way forward is to define a new resource for pull replications, or to add extra logic to check if only there is only a single item in the `replications` array and if so use the single replication endpoint.

EDIT: On further reflection my second suggestion sounds gross and difficult from an update point of view (i.e going from a single push replication to multiple)

**Comment by figadore** [comment]
My problem appears to be similar, although my `repo_key` is set to a local repo, as I'm trying to set up push replication. It returns 
> PUT https://[artifactory-server]/artifactory/api/replications/multiple/[local-repo]: 403 [{Status:403 Message:Multi-push replication is only available with an Enterprise license.}]

but I don't want multi-push. Assuming these have the same cause, I'm hoping to expand the scope of this issue a bit and get these cases both fixed at once
