### ISSUE TITLE
Manage SSL certificates

### ISSUE THREAD

**Issue by bodgit** [atlassian/terraform-provider-artifactory#38]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The remote repository resource appears to have support for using an existing SSL client certificate, but there doesn't appear to be a way to manage the certificate itself. We use these to authenticate to upstream Red Hat Yum repositories.

Happy to try and work on this myself.

### New or Affected Resource(s)

* artifactory_certificate (maybe?)

### Potential Terraform Configuration

Something like:

```hcl
resource artifactory_certificate "redhat" {
  alias   = "redhat"
  content = "${file("/path/to/file.pem")}"
}

resource artifactory_remote_repository "rhel7" {
  key                    = "rhel7"
  package_type           = "rpm"
  url                    = "https://cdn.redhat.com/..."
  client_tls_certificate = "${artifactory_certificate.redhat.alias}"
  ...
}
```

**Comment by dillon-giacoppo** [comment]
Looks like the field is already in the client library https://github.com/atlassian/go-artifactory/blob/master/artifactory/v1/repositories.go#L234

So to be able to use existing certs, you would only need to add a new string field.

To have terraform manage your certs, you need to add a resource which would be a little more intensive but should follow the same calling conventions as the other. The best place to start would be in looking at the operations here https://github.com/atlassian/go-artifactory/blob/master/artifactory/v1/security.go#L1005 and seeing how they map to CRUD operations in terraform. One of the only issues I see is that there is no read operation on a single certificate.

**Comment by bodgit** [comment]
I've recently added similar functionality to a Ruby Artifactory library so I'm familiar with the API. Create and Update are essentially the same, and Delete is obvious. Read is trickier a) as you've pointed out, you can only read all of the certificates in one go (however they should be easy to iterate over) and b) you can't read the certificate/private key back out again to compare it with what Terraform thinks the state should be. The only thing you can read out is the fingerprint, so you would need to perhaps compute the fingerprint on the file contents and compare it that way to see if it should trigger an update operation.
