### ISSUE TITLE
terraform 0.12 syntax problem

### ISSUE THREAD

**Issue by dextarr** [atlassian/terraform-provider-artifactory#43]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* artifactory_permission_target

### Terraform Configuration Files

```hcl
resource "artifactory_permission_target" "deploy" {
  name = "t012_Deploy"

  repo = {
    includes_pattern = ["**"]

    repositories = ["libs-dev", "libs-prod"]

    actions = {
      users = [
        {
          name        = "deployuser1"
          permissions = ["read", "annotate", "write", "delete"]
        },
        {
          name        = "deployuser2"
          permissions = ["read", "annotate", "write", "delete"]
        },
      ]

      groups = [
        {
          name        = "deploygroup1"
          permissions = ["read", "annotate", "write", "delete"]
        },
      ]
    }
  }
```

### Expected Behavior

permission should be created just as with terraform 0.11

### Actual Behavior

terraform plan (v0.12) stops with the error message below, but i'm not sure if this provider is 0.12 compatible. what would be the right syntax of the repo block for 0.12?

Error: Unsupported argument

  on permission.tf line 4, in resource "artifactory_permission_target" "deploy":
   4:   repo = {

An argument named "repo" is not expected here. Did you mean to define a block
of type "repo"?

### Steps to Reproduce

0. access to artifctory pro
1. `terraform plan`

### References

* #0000

**Comment by dillon-giacoppo** [comment]
So the provider will build for 0.12 in the next release which is currently being tested but you may also need to run `terraform 0.12upgrade`. See https://www.terraform.io/upgrade-guides/0-12.html. I don't know if there are any provider side changes we can do to fix this

**Comment by dextarr** [comment]
i did run `terraform 0.12upgrade` but that hasn't touch the repo block. i was hoping you can paste a valid repo block (or fix/extend the documentation) in relation to the 0.12 release. do you have an ETA for the release?

**Comment by jamestoyer** [comment]
@dextarr I've been working quite heavily with TF 0.12 and this provider recently. It looks like there is a syntax error in you TF that is causing it. There has been a subtle change in TF to the way it works out map/blocks which means your declaration no longer works the way it used to, see [here](https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks) for more info. 

You config should now look something like:
```hcl
resource "artifactory_permission_target" "deploy" {
  name = "t012_Deploy"

  repo {
    includes_pattern = ["**"]

    repositories = ["libs-dev", "libs-prod"]

    actions {
      users = [
        {
          name        = "deployuser1"
          permissions = ["read", "annotate", "write", "delete"]
        },
        {
          name        = "deployuser2"
          permissions = ["read", "annotate", "write", "delete"]
        },
      ]

      groups = [
        {
          name        = "deploygroup1"
          permissions = ["read", "annotate", "write", "delete"]
        },
      ]
    }
  }
```

It looks like the confusion here comes as the docs have not yet been updated to reflect this change in behaviour in TF 0.12

**Comment by dextarr** [comment]
@jamestoyer: actually i tried your suggestion before created the issue, but its not working.

using this _exact_ tf file... //hint: no need to replace the dummy provider-variables until the file get parsed correctly, which is not the case :(

```
provider "artifactory" {
  url     = "what"
  api_key = "ever"
}

resource "artifactory_permission_target" "deploy" {
  name = "t012_Deploy"

  repo {
    includes_pattern = ["**"]

    repositories = ["libs-dev", "libs-prod"]

    actions {
      users = [
        {
          name        = "deployuser1"
          permissions = ["read", "annotate", "write", "delete"]
        },
        {
          name        = "deployuser2"
          permissions = ["read", "annotate", "write", "delete"]
        },
      ]
      groups = [
        {
          name        = "deploygroup1"
          permissions = ["read", "annotate", "write", "delete"]
        },
      ]
    }
  }
}
```
i still have error messages for the inner blocks during `terraform plan`:
```
Error: Unsupported argument

  on main.tf line 15, in resource "artifactory_permission_target" "deploy":
  15:       users = [

An argument named "users" is not expected here. Did you mean to define a block
of type "users"?


Error: Unsupported argument

  on main.tf line 25, in resource "artifactory_permission_target" "deploy":
  25:       groups = [

An argument named "groups" is not expected here. Did you mean to define a
block of type "groups"?

```
suggestions?

**Comment by jamestoyer** [comment]
I believe that's also wrapped up into "breaking" changes in the 0.12 API. 

Could you try:
```hcl
provider "artifactory" {
  url     = "what"
  api_key = "ever"
}

resource "artifactory_permission_target" "deploy" {
  name = "t012_Deploy"

  repo {
    includes_pattern = ["**"]

    repositories = ["libs-dev", "libs-prod"]

    actions {
      users {
        name        = "deployuser1"
        permissions = ["read", "annotate", "write", "delete"]
      }

      users {
        name        = "deployuser2"
        permissions = ["read", "annotate", "write", "delete"]
      }

      groups {
        name        = "deploygroup1"
        permissions = ["read", "annotate", "write", "delete"]
      }
    }
  }
}
```

If that works, we can look at changing the names to make more sense. I'm generally using it in a dynamic block so I believe the below is syntactically the same as:

```hcl
resource "artifactory_permission_target" "foo" {
  name = var.name

  repo {
    includes_pattern = var.includes_pattern
    excludes_pattern = var.excludes_pattern
    repositories     = var.repositories

    actions {
      dynamic "groups" {
        for_each = var.groups
        content {
          name        = groups.value.name
          permissions = groups.value.permissions
        }
      }
      dynamic "users" {
        for_each = var.users
        content {
          name        = users.value.name
          permissions = users.value.permissions
        }
      }
    }
  }
}
```

**Comment by dextarr** [comment]
yes, now it's working as expected, thanks @jamestoyer!

**Comment by jamestoyer** [comment]
I'm going to close this out. I've opened #48 to track changing the names
