### ISSUE TITLE
Can create but not update remote repos

### ISSUE THREAD

**Issue by lexual** [atlassian/terraform-provider-artifactory#52]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.14

using plugin 1.6.3

artifactory.version:  6.11.1

### Affected Resource(s)

* artifactory_remote_repositories

### Terraform Configuration Files

```hcl
resource "artifactory_remote_repository" "TestyMcTestTest" {
  key = "TestyMcTestTest"
  package_type = "generic"
  url = "http://dl-cdn.alpinelinux.org/"
  repo_layout_ref = "simple-default"
}
```

Can create this, but when I go to amend anything, e.g. url, I get errors complaining about 400 returns from api with an unhelpful error message.

```hcl
resource "artifactory_remote_repository" "TestyMcTestTest" {
  key = "TestyMcTestTest"
  package_type = "generic"
  url = "http://dl-cdn.alpinelinux.org/foo-bar"
  repo_layout_ref = "simple-default"
}
```
### Debug Output

```
1 error occurred:
        * artifactory_remote_repository.TestyMcTestTest: 1 error occurred:
        * artifactory_remote_repository.TestyMcTestTest: POST https://MY_URL_FOR_ARTIFACTORY/api/repositories/TestyMcTestTest: 400 [{Status:400 Message:null
}]
```

### Steps to Reproduce

create remote repo, change anything, and try to apply.

Would love if anyone else can reproduce.

Any tips on how to get details of POST info being submitted??

### References

* #0000

**Comment by lexual** [comment]
OK, I think technically the problem lies with JFrog's API, but we should fix here, because otherwise the remoteRepo part of the provider is relatively useless.

With the API and remoteRepos, in particular circumstances, you can give identical JSON that specifies the remote repo config to do a create and an update call, and the create call will execute successfully, while the update (even though it has the same config as the create call) fails.

Specifically it appears to be tied to it not likely specific "options" that are only relevant to particular types of remote repos.

Below is a list of 7 flags, that will cause a "generic" remoteRepo update API call to fail.

* vcsType (vcs only)
* vcsGitProvider (vcs only)
* vcsGitDownloadUrl (vcs only)
* feedContextPath (nuget only)
* downloadContextPath (nuget only)
* v3FeedUrl (nuget only)
* bowerRegistryUrl (bower only)

So the solution is for update calls for remote repo, to only include these flags if we are dealing with those particular types of repo: vcs/nuget/bower .

**Comment by jamestoyer** [comment]
@lexual have you tried this with the latest codebase? It looks like your fork is a few commits behind master and there have been some changes to the way the provider gets references to values. It's possible these changes will actually fix the issues you're seeing.

If they don't feel free to update #53 to make them work 🙂

**Comment by lexual** [comment]
Does look to be resolved in later commits ;)
