### ISSUE TITLE
Support Terraform 0.12

### ISSUE THREAD

**Issue by lexual** [atlassian/terraform-provider-artifactory#58]
It appears the provider doesn't work with Terraform 0.12.

**Comment by jamestoyer** [comment]
Currently the pre-built binaries don't have 0.12 support. However, if you build from master, you should be able to use it with TF 0.12. 

I'm working this week on getting an automated process for building and publishing the binaries. My aim is to cut a new release this week to

**Comment by jamestoyer** [comment]
So I've published a new pre-release version [v2.0.0-alpha1](https://github.com/atlassian/terraform-provider-artifactory/releases/tag/v2.0.0-alpha1). You can get binaries from there that will support 0.12
