### ISSUE TITLE
Publish binaries

### ISSUE THREAD

**Issue by asvoboda** [atlassian/terraform-provider-artifactory#59]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, ever user needs to compile their own artifacts and either publish them into their own artifact store or just check in hand built binaries. I think it would be friendly to have the CI system build and publish releases for the community to use.

In an ideal world these would be published to the module registry so everything "just works". However, I understand there is additional friction associated with getting new modules to work there. So as a start, it might be nice to use either an OSS publishing location like bintray, or maybe Github packages?

**Comment by jamestoyer** [comment]
I'm all for this. I'm hoping to see if I can work something out this week or next. I know this has been on @dillon-giacoppo's list for a while. 

It'd be cool if we could make it work with GitHub actions as well

**Comment by asvoboda** [comment]
🚀 🎸
