### ISSUE TITLE
artifactory_certificate testcase is wrongly configured

### ISSUE THREAD

**Issue by volkc-basf** [atlassian/terraform-provider-artifactory#64]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

all

### Affected Resource(s)

* artifactory_certificate

### Expected Behavior

[CheckDestroy ](https://github.com/atlassian/terraform-provider-artifactory/blob/edfaff3bf7350aeaa4321910a487fe2fb37e31cb/pkg/artifactory/resource_artifactory_certificate_test.go#L54)should execute [testAccCheckCertificateDestroy](https://github.com/atlassian/terraform-provider-artifactory/blob/edfaff3bf7350aeaa4321910a487fe2fb37e31cb/pkg/artifactory/resource_artifactory_certificate_test.go#L72)

### Actual Behavior

It acutally refers to [testAccCheckUserDestroy](https://github.com/atlassian/terraform-provider-artifactory/blob/edfaff3bf7350aeaa4321910a487fe2fb37e31cb/pkg/artifactory/resource_artifactory_user_test.go#L69)

**Comment by bodgit** [comment]
Good catch, I must have started with the user tests as the basis for the certificate ones, and it manages to pass as it tries to find a user with the certificate ID so it assumes it was deleted.

I'll create a small PR to fix this.
