### ISSUE TITLE
Link to docs website

### ISSUE THREAD

**Issue by ryanwholey** [atlassian/terraform-provider-artifactory#69]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Could we add a link to the documentation in the readme? I'm having trouble finding the documentation, couldn't find it on the atlassian website either. I've been using the website raw markdown but I'm sure it looks much nicer wherever it's hosted. 

If the docs are not hosted, can I build/run them locally? How might someone do that?

Thanks

**Comment by volkc-basf** [comment]
Hey @ryanwholey,

are you looking for [this](https://github.com/atlassian/terraform-provider-artifactory/blob/master/website/docs/index.html.markdown)?

Best,
Chris

**Comment by ryanwholey** [comment]
Hi @volkc-basf, 
These work great, thanks. I notice there's a section for layout and page title etc at the top leading me to wonder if these are hosted somewhere? If not, how would you feel about adding the link you posted here to the readme?
