### ISSUE TITLE
Need ability to create Smart Remote Repository by supporting 'contentSynchronisation' argument

### ISSUE THREAD

**Issue by AshutoshNirkhe** [atlassian/terraform-provider-artifactory#76]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently terraform-provider-artifactory v2.0.0-alpha1 **doesn't support an argument called 'contentSynchronisation'** that is necessary for creating a 'Smart Remote Repository' in JFrog Artifactory (It's a must for Artifactory Edge license).  
Ref : REST API section at the bottom of link - https://www.jfrog.com/confluence/display/JFROG/Smart+Remote+Repositories

Because of this we are getting below error in terraform apply -
**Status:400 Message:Only smart remote repositories are supported with Artifactory Edge license**

It will be great if you could add this support as this is available via JFrog REST API!

### New or Affected Resource(s)

* artifactory_remote_repository

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "artifactory_remote_repository" "smart-remote-repo" {
  key             = "my-smart-remote-repo"
  package_type    = "generic"
  url             = "https://my-jfrog.org/artifactory/generic-local-repo"
  repo_layout_ref = "simple-default"   
  content_synchronisation = {
    enabled = true,
    statistics = {
      enabled = true
    },
    properties = {
      enabled = false
    },
    source = {
      originAbsenceDetection = false
    }
  }
}

```

### References

https://www.jfrog.com/confluence/display/JFROG/Smart+Remote+Repositories

* #0000

**Comment by AshutoshNirkhe** [comment]
I have raised the PR for this issue here, please review -
https://github.com/atlassian/terraform-provider-artifactory/pull/77/files

**Comment by djsly** [comment]
This can be closed I think

**Comment by AshutoshNirkhe** [comment]
Closing, as the PR is merged and we are able to create remote repos after that.
