### ISSUE TITLE
Support mTLS for HTTP SSO

### ISSUE THREAD

**Issue by skolyszewski** [atlassian/terraform-provider-artifactory#93]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Corporate environments often rely on PKI. There's currently no way of using the provider (without rebuilding) in a situation when HTTP SSO is used with in conjunction with mTLS (client side TLS auth). Also, allowing using custom CaCertsPool would be necessary. 

### New or Affected Resource(s)

None

### Potential Terraform Configuration

Three env variables for provider configuration, e.g.:
* ARTIFACTORY_KEY
* ARTIFACTORY_CERT
* ARTIFACTORY_CA

### References

None

**Comment by peters95** [comment]
Migrated -> https://github.com/jfrog/terraform-provider-artifactory/issues/21

**Comment by chb0github** [comment]
I'd like to address this issue on the new repo @gskolysz Migrated -> [jfrog](https://github.com/jfrog/terraform-provider-artifactory/issues/21)
